### ISSUE TITLE
(QUESTION) Integrate it in blender ? (EEVEE RENDER AND CYCLES RENDER

### ISSUE THREAD

**Issue by DonovaneH** [SungJJinKang/EveryCulling#1]
Hello i have question about your work, are you able to integrate your culling work on Blender 3.0 versions with a customisable panel for manage distance culling etc ? on Eevee Render engine first and if is it possible in Cycles render engine

(I know is the wrong platform to ask this question but i search since a long time a c++ dev able to integrate a culling option in blender ... i know it's a good idea for a lot a reasons and for the big high poly meshes ! i know is the futur since i seen the nvidia meshlets (mesh shader) and recently Mesh primitives on PS5 And xbox one )

First i just want your culling write (EveryCulling), and in the future i want an alternative like Nanite ue5 or use Vk or DX12 API for use directly mesh shader by Nvidia 

if you are open i want talk with you :) for create this project if you are ok :)

Thank you for your response :)

**Comment by SungJJinKang** [comment]
Sorry, I don't have plan to do it.
If you want, you can do it.

I don't recommend it. I think this library is not suitable for integrating with other programs...
Because I made this library only use for my in-house game engine. So It's not easy to integrate with blender...
Maybe You can find better library to do it.

**Comment by DonovaneH** [comment]
oh ok :/ i'm not a c++ dev i'm a web dev, i'm searching a c++ dev for make this, but i don't find it :/
